DROP TABLE IF EXISTS VaccineType CASCADE; 
 
DROP TABLE IF EXISTS Manufacturer CASCADE; 
 
DROP TABLE IF EXISTS VaccinationStations CASCADE; 
 
DROP TABLE IF EXISTS VaccineBatch CASCADE; 
 
 
DROP TABLE IF EXISTS TransportationLog CASCADE; 
 
DROP TABLE IF EXISTS StaffMembers CASCADE; 
 
DROP TABLE IF EXISTS Shifts CASCADE; 
 
DROP TABLE IF EXISTS Vaccinations CASCADE; 
 
DROP TABLE IF EXISTS Patients CASCADE; 
 
DROP TABLE IF EXISTS VaccinePatients CASCADE; 
 
DROP TABLE IF EXISTS Symptoms CASCADE; 
 
DROP TABLE IF EXISTS Diagnosis CASCADE; 